#goal definition
geometry_msgs/Point target
float32 speed
builtin_interfaces/Duration time_allowance
float64 acc
float64 dec
bool check_collision
---
#result definition
geometry_msgs/PoseStamped docking_point
builtin_interfaces/Duration total_elapsed_time
---
#feedback definition
float32 distance_traveled
