#goal definition
geometry_msgs/PoseStamped pose
bool is_reverse
float32 distance_goal_tolerance
float32 yaw_goal_tolerance
float64 position_p
float64 position_i
float64 position_d
float64 orientation_p
float64 orientation_i
float64 orientation_d
float64 max_linear_velocity
float64 max_angular_velocity
bool reverse_yaw
bool heading_only
string target_tf_frame
float64 max_linear;
float64 max_angular;
float64 scale_factor;
float64 distance_max;

builtin_interfaces/Duration time_allowance
---
#result definition
builtin_interfaces/Duration total_elapsed_time
geometry_msgs/PoseStamped docking_point

---
#feedback definition
float32 current_x
float32 current_y