#goal definition
float32 target_x
float32 target_y
float32 target_yaw
builtin_interfaces/Duration time_allowance
---
#result definition
builtin_interfaces/Duration total_elapsed_time
---
#feedback definition
float32 current_x
float32 current_y